### PR TITLE
fix #380/shouldUseEnrichEndpoint respect enrich value

### LINKED ISSUE #380: Cannot turn off enrichment on client side.
https://github.com/GetStream/stream-js/blob/fe8ceab34f28c7a1f441a398d1ccbc1a9932bfbc/src/client.ts#L196

Because on the client side enrichByDefault is true since we are not using an api secret.
Then passing
`feed.get({ enrich: false })`
leads to 
```
    if (options.enrich) {
      const result = options.enrich;
      delete options.enrich;
      return result;
    }
```
not entering the if and therefore always using enrichByDefault which is true.

https://github.com/GetStream/stream-js/blob/fe8ceab34f28c7a1f441a398d1ccbc1a9932bfbc/src/client.ts#L501

gz#5974

### PR DESCRIPTION
**Pull request by mahboubii**

### CODE REVIEW

**Comment by sanchaz** [comment]
enrichByDefault -> true
shouldUseEnrichEndpoint receives as params
`{ enrich: false, ownReactions: true }`

What should shouldUseEnrichEndpoint return?

- If it should be false, then yes, this fixes it.
- If it should be true, then no because it will return immediately and not check ownReactions.

Either way this fixes my issue.

**Comment by mahboubii** [comment]
> enrichByDefault -> true
> shouldUseEnrichEndpoint receives as params
> `{ enrich: false, ownReactions: true }`
> 
> What should shouldUseEnrichEndpoint return?
> 
> * If it should be false, then yes, this fixes it.
> * If it should be true, then no because it will return immediately and not check ownReactions.
> 
> Either way this fixes my issue.


IMO `enrich: false` is a more general option and has a higher priority than others

**Review by ferhatelmas — APPROVED** [review]
LGTM

**Comment by ferhatelmas** [comment]
> IMO enrich: false is a more general option and has a higher priority than others

That's correct.

if no enrich as url param (part of path), then no enrichment.

**Pull request merged**
